##
# ShopwareApi

-
  name:  'Shopware-Event-Api'
  uriPattern: 'sitegeist/goldengate/events/{@action}'
  defaults:
    '@package':    'Sitegeist.Goldengate.Neos.Api'
    '@controller': 'Event'
    '@format':     'json'

  httpMethods: ['POST', 'PUT']
