Sitegeist:
  GoldenGate:
    Neos:
      Api:
        enableCache: true

        shops:
          default:
            title: 'Default Shop'

            protocol: ~
            host: ~
            port: ~
            base: ~

            user: ~
            password: ~

        log:
          logger: Neos\Flow\Log\Logger
          backend: Neos\Flow\Log\Backend\FileBackend
          backendOptions:
             logFileURL: '%FLOW_PATH_DATA%Logs/Goldengate.log'
             createParentDirectories: TRUE
             severityThreshold: '%LOG_ERR%'
             maximumLogFileSize: 10485760
             logFilesToKeep: 1
             logMessageOrigin: FALSE

Neos:
  Fusion:
    defaultContext:
      Shopware.Api: 'Sitegeist\GoldenGate\Neos\Api\Eel\ApiHelper'
      Shopware.Caching: 'Sitegeist\GoldenGate\Neos\Api\Eel\CachingHelper'

  Flow:
    mvc:
      routes:
        Sitegeist.GoldenGate.Neos.Api:
          position: 'before Neos.Neos'
