Sitegeist:
  GoldenGate:
    Neos:
      Api:
        #
        # Enable caching of api-requests
        #
        enableCache: true

        #
        # Available shopware-connections. By default the `default` key will be used if nothing
        # else is defined.
        #
        shops:

          default:
            title: 'Default Shop'

            protocol: ~
            host: ~
            port: ~
            base: ~

            user: ~
            password: ~

        #
        # Shopware API Logger
        #
        log:
          logger: Neos\Flow\Log\Logger
          backend: Neos\Flow\Log\Backend\FileBackend
          backendOptions:
             logFileURL: '%FLOW_PATH_DATA%Logs/Sitegeist_GoldenGate_Api.log'
             createParentDirectories: TRUE
             severityThreshold: '%LOG_ERR%'
             maximumLogFileSize: 10485760
             logFilesToKeep: 1
             logMessageOrigin: FALSE

Neos:
  Fusion:
    defaultContext:
      Shopware.Api: 'Sitegeist\GoldenGate\Neos\Api\Eel\ApiHelper'
      Shopware.Caching: 'Sitegeist\GoldenGate\Neos\Api\Eel\CachingHelper'

  Flow:
    mvc:
      routes:
        Sitegeist.GoldenGate.Neos.Api:
          position: 'before Neos.Neos'
