Sitegeist:
  GoldenGate:
    Neos:
      Api:
        log:
          backendOptions:
            logFileURL: '%FLOW_PATH_DATA%Logs/Sitegeist_GoldenGate_Api_Development.log'
            severityThreshold: '%LOG_INFO%'
